import './globals.css'
import Navbar from '../components/navbar';
import FooterSection from '../components/footer';
import {Contact} from '../components/contact';
import PageWrapper from '@/components/wrapper';


export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

import { Breadcrumb, Layout, Menu, theme } from 'antd';
const { Header, Content, Footer } = Layout;

export default function RootLayout({
  children
}) {
  return (
    <html lang="en">
      <body className='transition font-ysabeau'>{children}

      <Layout className="layout h-full">
      

      <Contact/>
      <Footer
      className='p-0'
        style={{
          textAlign: 'center',
        }}
      >
<FooterSection/>      </Footer>
    </Layout>

      </body>
    </html>
  )
}
