import './globals.css'
import type { Metadata } from 'next'
import Navbar from '../components/navbar';
import FooterSection from '../components/footer';
import {Contact} from '../components/contact';
import PageWrapper from '@/components/wrapper';




export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className='transition font-ysabeau'>{children}

      <Contact/>

      </body>
    </html>
  )
}
