import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Navbar from '../components/navbar';
import FooterSection from '../components/footer';
import {Contact} from '../components/contact';
import { Breadcrumb, Layout, Menu, theme } from 'antd';
const { Header, Content, Footer } = Layout;

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className='transition font-ysabeau'>
        
    <Layout className="layout h-full">
      
      <Navbar/>
            <Content>
              <div
                className="site-layout-content"
                style={{
                  background: colorBgContainer,
                }}
              >
        {children}
      
      
      
<Contact/>
        </div>
      </Content>
      <Footer
      className='p-0'
        style={{
          textAlign: 'center',
        }}
      >
<FooterSection/>      </Footer>
    </Layout>
      </body>
    </html>
  )
}
